export type Crypto = { code: string; name: string };

// Curated list of well-known cryptocurrencies (codes match common ticker symbols).
export const CRYPTOS: Crypto[] = [
  { code: "BTC", name: "Bitcoin" },
  { code: "ETH", name: "Ethereum" },
  { code: "USDT", name: "Tether" },
  { code: "BNB", name: "BNB" },
  { code: "SOL", name: "Solana" },
  { code: "USDC", name: "USD Coin" },
  { code: "XRP", name: "XRP" },
  { code: "DOGE", name: "Dogecoin" },
  { code: "TON", name: "Toncoin" },
  { code: "ADA", name: "Cardano" },
  { code: "TRX", name: "TRON" },
  { code: "AVAX", name: "Avalanche" },
  { code: "SHIB", name: "Shiba Inu" },
  { code: "DOT", name: "Polkadot" },
  { code: "LINK", name: "Chainlink" },
  { code: "BCH", name: "Bitcoin Cash" },
  { code: "MATIC", name: "Polygon" },
  { code: "LTC", name: "Litecoin" },
  { code: "NEAR", name: "NEAR Protocol" },
  { code: "UNI", name: "Uniswap" },
  { code: "ICP", name: "Internet Computer" },
  { code: "APT", name: "Aptos" },
  { code: "XLM", name: "Stellar" },
  { code: "ETC", name: "Ethereum Classic" },
  { code: "ATOM", name: "Cosmos" },
  { code: "XMR", name: "Monero" },
  { code: "OKB", name: "OKB" },
  { code: "FIL", name: "Filecoin" },
  { code: "HBAR", name: "Hedera" },
  { code: "ARB", name: "Arbitrum" },
  { code: "VET", name: "VeChain" },
  { code: "MKR", name: "Maker" },
  { code: "OP", name: "Optimism" },
  { code: "GRT", name: "The Graph" },
  { code: "AAVE", name: "Aave" },
  { code: "ALGO", name: "Algorand" },
  { code: "SAND", name: "The Sandbox" },
  { code: "MANA", name: "Decentraland" },
  { code: "EOS", name: "EOS" },
  { code: "XTZ", name: "Tezos" },
  { code: "FLOW", name: "Flow" },
  { code: "AXS", name: "Axie Infinity" },
  { code: "CRO", name: "Cronos" },
  { code: "FTM", name: "Fantom" },
  { code: "RUNE", name: "THORChain" },
  { code: "SUI", name: "Sui" },
  { code: "INJ", name: "Injective" },
  { code: "LDO", name: "Lido DAO" },
  { code: "IMX", name: "Immutable" },
  { code: "PEPE", name: "Pepe" },
  { code: "RNDR", name: "Render" },
  { code: "TIA", name: "Celestia" },
  { code: "SEI", name: "Sei" },
  { code: "FET", name: "Fetch.ai" },
  { code: "STX", name: "Stacks" },
  { code: "QNT", name: "Quant" },
  { code: "KAS", name: "Kaspa" },
  { code: "MINA", name: "Mina" },
  { code: "GALA", name: "Gala" },
  { code: "CHZ", name: "Chiliz" },
  { code: "DASH", name: "Dash" },
  { code: "ZEC", name: "Zcash" },
  { code: "COMP", name: "Compound" },
  { code: "SNX", name: "Synthetix" },
  { code: "CRV", name: "Curve DAO" },
  { code: "ENJ", name: "Enjin Coin" },
  { code: "BAT", name: "Basic Attention" },
  { code: "ZIL", name: "Zilliqa" },
  { code: "1INCH", name: "1inch" },
  { code: "YFI", name: "yearn.finance" },
  { code: "SUSHI", name: "SushiSwap" },
];
